# Company_Data

In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.ensemble import RandomForestClassifier as RF
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix


In [2]:
df=pd.read_csv('Company_Data.csv')

In [3]:
df

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0     9.50        138      73           11         276    120       Bad   42   
1    11.22        111      48           16         260     83      Good   65   
2    10.06        113      35           10         269     80    Medium   59   
3     7.40        117     100            4         466     97    Medium   55   
4     4.15        141      64            3         340    128       Bad   38   
..     ...        ...     ...          ...         ...    ...       ...  ...   
395  12.57        138     108           17         203    128      Good   33   
396   6.14        139      23            3          37    120    Medium   55   
397   7.41        162      26           12         368    159    Medium   40   
398   5.94        100      79            7         284     95       Bad   50   
399   9.71        134      37            0          27    120      Good   49   

     Education Urban   US  
0           17   Yes  Yes  
1           10   Yes  Yes  
2           12   Yes  Yes  
3           14   Yes  Yes  
4           13   Yes   No  
..         ...   ...  ...  
395         14   Yes  Yes  
396         11    No  Yes  
397         18   Yes  Yes  
398         12   Yes  Yes  
399         16   Yes  Yes  

[400 rows x 11 columns]

In [4]:
df.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [6]:
df.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [7]:
df1 = pd.get_dummies(df, columns = ['ShelveLoc','Urban','US'])

In [8]:
df1

Sales  CompPrice  Income  Advertising  Population  Price  Age  Education  \
0     9.50        138      73           11         276    120   42         17   
1    11.22        111      48           16         260     83   65         10   
2    10.06        113      35           10         269     80   59         12   
3     7.40        117     100            4         466     97   55         14   
4     4.15        141      64            3         340    128   38         13   
..     ...        ...     ...          ...         ...    ...  ...        ...   
395  12.57        138     108           17         203    128   33         14   
396   6.14        139      23            3          37    120   55         11   
397   7.41        162      26           12         368    159   40         18   
398   5.94        100      79            7         284     95   50         12   
399   9.71        134      37            0          27    120   49         16   

     ShelveLoc_Bad  ShelveLoc_Good  ShelveLoc_Medium  Urban_No  Urban_Yes  \
0                1               0                 0         0          1   
1                0               1                 0         0          1   
2                0               0                 1         0          1   
3                0               0                 1         0          1   
4                1               0                 0         0          1   
..             ...             ...               ...       ...        ...   
395              0               1                 0         0          1   
396              0               0                 1         1          0   
397              0               0                 1         0          1   
398              1               0                 0         0          1   
399              0               1                 0         0          1   

     US_No  US_Yes  
0        0       1  
1        0       1  
2        0       1  
3        0       1  
4        1       0  
..     ...     ...  
395      0       1  
396      0       1  
397      0       1  
398      0       1  
399      0       1  

[400 rows x 15 columns]

In [9]:
#target variable is continious, we create a class of the value based on the mean
#<= 7.49 == "Small" and > 7.49 == "large"

In [10]:
df1["sales"]="small"
df1.loc[df1["Sales"]>7.49,"sales"]="large"
df1.drop(["Sales"],axis=1,inplace=True)

In [11]:
df1

CompPrice  Income  Advertising  Population  Price  Age  Education  \
0          138      73           11         276    120   42         17   
1          111      48           16         260     83   65         10   
2          113      35           10         269     80   59         12   
3          117     100            4         466     97   55         14   
4          141      64            3         340    128   38         13   
..         ...     ...          ...         ...    ...  ...        ...   
395        138     108           17         203    128   33         14   
396        139      23            3          37    120   55         11   
397        162      26           12         368    159   40         18   
398        100      79            7         284     95   50         12   
399        134      37            0          27    120   49         16   

     ShelveLoc_Bad  ShelveLoc_Good  ShelveLoc_Medium  Urban_No  Urban_Yes  \
0                1               0                 0         0          1   
1                0               1                 0         0          1   
2                0               0                 1         0          1   
3                0               0                 1         0          1   
4                1               0                 0         0          1   
..             ...             ...               ...       ...        ...   
395              0               1                 0         0          1   
396              0               0                 1         1          0   
397              0               0                 1         0          1   
398              1               0                 0         0          1   
399              0               1                 0         0          1   

     US_No  US_Yes  sales  
0        0       1  large  
1        0       1  large  
2        0       1  large  
3        0       1  small  
4        1       0  small  
..     ...     ...    ...  
395      0       1  large  
396      0       1  small  
397      0       1  small  
398      0       1  small  
399      0       1  large  

[400 rows x 15 columns]

In [12]:
x = df1.iloc[:,0:14]
y = df1.iloc[:,14]

In [13]:
x

CompPrice  Income  Advertising  Population  Price  Age  Education  \
0          138      73           11         276    120   42         17   
1          111      48           16         260     83   65         10   
2          113      35           10         269     80   59         12   
3          117     100            4         466     97   55         14   
4          141      64            3         340    128   38         13   
..         ...     ...          ...         ...    ...  ...        ...   
395        138     108           17         203    128   33         14   
396        139      23            3          37    120   55         11   
397        162      26           12         368    159   40         18   
398        100      79            7         284     95   50         12   
399        134      37            0          27    120   49         16   

     ShelveLoc_Bad  ShelveLoc_Good  ShelveLoc_Medium  Urban_No  Urban_Yes  \
0                1               0                 0         0          1   
1                0               1                 0         0          1   
2                0               0                 1         0          1   
3                0               0                 1         0          1   
4                1               0                 0         0          1   
..             ...             ...               ...       ...        ...   
395              0               1                 0         0          1   
396              0               0                 1         1          0   
397              0               0                 1         0          1   
398              1               0                 0         0          1   
399              0               1                 0         0          1   

     US_No  US_Yes  
0        0       1  
1        0       1  
2        0       1  
3        0       1  
4        1       0  
..     ...     ...  
395      0       1  
396      0       1  
397      0       1  
398      0       1  
399      0       1  

[400 rows x 14 columns]

In [14]:
y

0      large
1      large
2      large
3      small
4      small
       ...  
395    large
396    small
397    small
398    small
399    large
Name: sales, Length: 400, dtype: object

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(x,y,test_size=0.20,random_state=12)

In [16]:
#Training data 
X_train.shape , y_train.shape

((320, 14), (320,))

In [17]:
#Test Data
X_test.shape , y_test.shape

((80, 14), (80,))

### model training 

In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import GradientBoostingClassifier
rf_model = RandomForestClassifier()
rf_model.fit(X_train,y_train)

RandomForestClassifier()

In [19]:
gb_model = GradientBoostingClassifier()
gb_model.fit(X_train,y_train)

GradientBoostingClassifier()

### GridSearch CV

In [20]:
from sklearn.model_selection import GridSearchCV

In [21]:
grid_search = GridSearchCV(estimator=rf_model,param_grid = {'max_depth': [4,5,6,7,8],'criterion':['gini','entropy']},cv=5)
grid_search.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=RandomForestClassifier(),
             param_grid={'criterion': ['gini', 'entropy'],
                         'max_depth': [4, 5, 6, 7, 8]})

In [22]:
grid_search.best_params_

{'criterion': 'gini', 'max_depth': 7}

In [23]:
grid_search.best_score_

0.796875

In [24]:
grid_search_gb = GridSearchCV(estimator=gb_model,param_grid = {'max_depth': [4,5,6,7,8]},cv=5)
grid_search_gb.fit(X_train,y_train)

GridSearchCV(cv=5, estimator=GradientBoostingClassifier(),
             param_grid={'max_depth': [4, 5, 6, 7, 8]})

In [25]:
grid_search_gb.best_params_

{'max_depth': 4}

In [26]:
grid_search_gb.best_score_

0.790625

In [27]:
rf_model = RandomForestClassifier(n_estimators=100,criterion='entropy',max_depth=7)  #by using Gridcv
rf_model.fit(X_train,y_train)

RandomForestClassifier(criterion='entropy', max_depth=7)

In [28]:
gb_model = GradientBoostingClassifier(n_estimators=100,max_depth=4) #by using grid search cv
gb_model.fit(X_train,y_train)

GradientBoostingClassifier(max_depth=4)

### model testing with rf model

In [29]:
#Training data
y_train_pred_rf = rf_model.predict(X_train) 

In [30]:
#Test data
y_test_pred_rf = rf_model.predict(X_test) 

### model testing with gb model

In [31]:
#Training data
y_train_pred_gb = gb_model.predict(X_train) 

In [32]:
#Test data
y_test_pred_gb = gb_model.predict(X_test) 

### evaluation metrics

In [33]:
from sklearn.metrics import accuracy_score,confusion_matrix,precision_score,recall_score,classification_report

In [34]:
print(classification_report(y_train,y_train_pred_rf))

              precision    recall  f1-score   support

       large       0.99      0.96      0.98       159
       small       0.96      0.99      0.98       161

    accuracy                           0.98       320
   macro avg       0.98      0.98      0.98       320
weighted avg       0.98      0.98      0.98       320



In [35]:
print(classification_report(y_test,y_test_pred_rf))

              precision    recall  f1-score   support

       large       0.88      0.70      0.78        40
       small       0.75      0.90      0.82        40

    accuracy                           0.80        80
   macro avg       0.81      0.80      0.80        80
weighted avg       0.81      0.80      0.80        80



In [36]:
#Training Data 
accuracy_score(y_train,y_train_pred_gb)

1.0

In [37]:
confusion_matrix(y_train,y_train_pred_gb)

array([[159,   0],
       [  0, 161]], dtype=int64)

In [38]:
#TEST DATA
accuracy_score(y_test,y_test_pred_gb)

0.8

In [39]:
confusion_matrix(y_test,y_test_pred_gb)

array([[31,  9],
       [ 7, 33]], dtype=int64)

In [40]:
print(classification_report(y_train,y_train_pred_gb))

              precision    recall  f1-score   support

       large       1.00      1.00      1.00       159
       small       1.00      1.00      1.00       161

    accuracy                           1.00       320
   macro avg       1.00      1.00      1.00       320
weighted avg       1.00      1.00      1.00       320



In [41]:
print(classification_report(y_test,y_test_pred_gb))

              precision    recall  f1-score   support

       large       0.82      0.78      0.79        40
       small       0.79      0.82      0.80        40

    accuracy                           0.80        80
   macro avg       0.80      0.80      0.80        80
weighted avg       0.80      0.80      0.80        80



In [42]:
rf_model.feature_importances_

array([0.10208046, 0.09121026, 0.10875166, 0.07871292, 0.23836724,
       0.10978838, 0.05330931, 0.0654002 , 0.07559842, 0.02379144,
       0.01114746, 0.00722845, 0.01663607, 0.01797773])

In [43]:
fi = pd.DataFrame({'feature': list(X_train.columns),
                   'importance': rf_model.feature_importances_}).\
                    sort_values('importance', ascending = False)

In [44]:
fi

feature  importance
4              Price    0.238367
5                Age    0.109788
2        Advertising    0.108752
0          CompPrice    0.102080
1             Income    0.091210
3         Population    0.078713
8     ShelveLoc_Good    0.075598
7      ShelveLoc_Bad    0.065400
6          Education    0.053309
9   ShelveLoc_Medium    0.023791
13            US_Yes    0.017978
12             US_No    0.016636
10          Urban_No    0.011147
11         Urban_Yes    0.007228

In [45]:
#price col is important feature

In [46]:
gb_model.feature_importances_

array([0.15613235, 0.07391146, 0.1258557 , 0.02521021, 0.30958483,
       0.09695944, 0.0198539 , 0.06516163, 0.11540104, 0.00512491,
       0.0015461 , 0.00234467, 0.00081534, 0.00209843])

In [47]:
fi_gb = pd.DataFrame({'feature': list(X_train.columns),
                   'importance': gb_model.feature_importances_}).\
                    sort_values('importance', ascending = False)

In [48]:
fi_gb

feature  importance
4              Price    0.309585
0          CompPrice    0.156132
2        Advertising    0.125856
8     ShelveLoc_Good    0.115401
5                Age    0.096959
1             Income    0.073911
7      ShelveLoc_Bad    0.065162
3         Population    0.025210
6          Education    0.019854
9   ShelveLoc_Medium    0.005125
11         Urban_Yes    0.002345
13            US_Yes    0.002098
10          Urban_No    0.001546
12             US_No    0.000815

In [49]:
##price col is important feature